import { NextResponse } from 'next/server'
import { Octokit } from '@octokit/rest'

export async function POST(request: Request) {
    try {
        const { repoName, userId, planType, githubToken } = await request.json()

        if (!githubToken) {
            return NextResponse.json({ error: 'Missing GitHub Token' }, { status: 401 })
        }

        if (!['leetcode', 'enterprise'].includes(planType)) {
            return NextResponse.json({ error: 'Invalid plan type' }, { status: 400 })
        }

        const octokit = new Octokit({ auth: githubToken })

        // 1. Get user info
        const { data: user } = await octokit.users.getAuthenticated()
        const username = user.login

        // 2. Check if repo exists
        try {
            await octokit.repos.get({ owner: username, repo: repoName })
            console.log(`Repo ${repoName} already exists`)

            // If exists, just return success
            return NextResponse.json({
                success: true,
                message: 'Repository already exists',
                repo_url: `https://github.com/${username}/${repoName}`
            })
        } catch (error: any) {
            if (error.status !== 404) throw error
        }

        // 3. Create repo if not found
        console.log(`Creating repo ${repoName}...`)

        let description = 'Auto-generated repository by GitMaxer'
        let content = ''

        if (planType === 'leetcode') {
            description = 'My Daily LeetCode Solutions - Auto-generated by GitMaxer 🚀'
            content = `# 🚀 My LeetCode Journey\n\nThis repository contains my daily LeetCode solutions, automatically generated and committed by [GitMaxer](https://gitmaxer.com).\n\n## 📊 Statistics\n\n- **Languages:** Python, Java, C++, JavaScript\n- **Difficulty:** Easy, Medium, Hard\n\n## 📂 Structure\n\nSolutions are organized by difficulty level:\n\n- \`/Easy\`\n- \`/Medium\`\n- \`/Hard\`\n\nHappy Coding! 💻`
        } else {
            description = 'Enterprise Project - Managed by GitMaxer 💼'
            content = `# 💼 Enterprise Project\n\nThis is a professional project repository managed by GitMaxer Enterprise.\n\n## 🚀 Project Overview\n\nAuto-generated enterprise-grade code contributions.`
        }

        const { data: repo } = await octokit.repos.createForAuthenticatedUser({
            name: repoName,
            description,
            private: false, // Make it public by default for visibility (can be changed later)
            auto_init: true
        })

        // 4. Add initial README (if auto_init didn't do enough or we want custom content)
        // Note: auto_init=true creates an empty README. We can update it.
        try {
            await octokit.repos.createOrUpdateFileContents({
                owner: username,
                repo: repoName,
                path: 'README.md',
                message: 'docs: Add initial README',
                content: Buffer.from(content).toString('base64'),
                sha: await getFileSha(octokit, username, repoName, 'README.md')
            })
        } catch (e) {
            console.warn('Failed to update README:', e)
        }

        return NextResponse.json({
            success: true,
            message: 'Repository created successfully!',
            repo_url: repo.html_url
        })

    } catch (error: any) {
        console.error('API Error:', error)
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 })
    }
}

async function getFileSha(octokit: any, owner: string, repo: string, path: string) {
    try {
        const { data } = await octokit.repos.getContent({ owner, repo, path })
        return (data as any).sha
    } catch (e) {
        return undefined
    }
}
