import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export const dynamic = 'force-dynamic'

// Get service client for database access
function getServiceClient() {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
    const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!
    return createClient(supabaseUrl, serviceRoleKey, {
        auth: { persistSession: false, autoRefreshToken: false }
    })
}

export async function POST(request: Request) {
    try {
        const { repoName, userId, planType, githubToken: clientToken } = await request.json()

        if (!userId) {
            return NextResponse.json({ error: 'Missing userId' }, { status: 400 })
        }

        if (!['leetcode', 'enterprise', 'owner'].includes(planType)) {
            return NextResponse.json({ error: 'Invalid plan type' }, { status: 400 })
        }

        // Try to get GitHub token - prioritize client token, fallback to database
        let githubToken = clientToken

        if (!githubToken) {
            console.log('No client token provided, fetching from database...')
            const supabase = getServiceClient()
            const { data: settings, error } = await supabase
                .from('user_settings')
                .select('github_access_token')
                .eq('id', userId)
                .single()

            if (error || !settings?.github_access_token) {
                console.error('Could not retrieve token from database:', error)
                return NextResponse.json({
                    error: 'GitHub token not found. Please log out and log back in to refresh your authentication.'
                }, { status: 401 })
            }

            githubToken = settings.github_access_token
            console.log('GitHub token retrieved from database')
        }

        const headers = {
            'Authorization': `token ${githubToken}`,
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json'
        }

        // 1. Get user info
        console.log(`Getting GitHub user info...`)
        const userRes = await fetch('https://api.github.com/user', { headers })
        console.log(`GitHub User Status: ${userRes.status}`)
        if (!userRes.ok) {
            const errText = await userRes.text()
            console.error(`GitHub User Error: ${errText}`)
            throw new Error('Failed to fetch GitHub user')
        }
        const user = await userRes.json()
        const username = user.login
        console.log(`GitHub Username: ${username}`)

        // 2. Check if repo exists
        console.log(`Checking if repo ${repoName} exists...`)
        const checkRes = await fetch(`https://api.github.com/repos/${username}/${repoName}`, { headers })
        console.log(`Repo Check Status: ${checkRes.status}`)

        if (checkRes.ok) {
            console.log(`Repo ${repoName} already exists`)
            return NextResponse.json({
                success: true,
                message: 'Repository already exists',
                repo_url: `https://github.com/${username}/${repoName}`
            })
        }

        // 3. Create repo if not found
        console.log(`Creating repo ${repoName}...`)

        let description = 'Auto-generated repository by GitMaxer'
        let content = ''

        if (planType === 'leetcode' || planType === 'owner') {
            description = 'My Daily LeetCode Solutions - Auto-generated by GitMaxer 🚀'
            content = `# 🚀 My LeetCode Journey\n\nThis repository contains my daily LeetCode solutions, automatically generated and committed by [GitMaxer](https://gitmaxer.com).\n\n## 📊 Statistics\n\n- **Languages:** Python, Java, C++, JavaScript\n- **Difficulty:** Easy, Medium, Hard\n\n## 📂 Structure\n\nSolutions are organized by difficulty level:\n\n- \`/Easy\`\n- \`/Medium\`\n- \`/Hard\`\n\nHappy Coding! 💻`
        } else {
            description = 'Enterprise Project - Managed by GitMaxer 💼'
            content = `# 💼 Enterprise Project\n\nThis is a professional project repository managed by GitMaxer Enterprise.\n\n## 🚀 Project Overview\n\nAuto-generated enterprise-grade code contributions.`
        }

        const createRes = await fetch('https://api.github.com/user/repos', {
            method: 'POST',
            headers,
            body: JSON.stringify({
                name: repoName,
                description,
                private: false,
                auto_init: true
            })
        })

        if (!createRes.ok) {
            const err = await createRes.json()
            throw new Error(`Failed to create repo: ${err.message}`)
        }

        const repo = await createRes.json()

        // 4. Add initial README
        // We need to wait a moment for the repo to propagate or check SHA if auto_init created one
        try {
            // Get SHA of existing README (created by auto_init)
            const readmeRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/contents/README.md`, { headers })
            let sha = undefined
            if (readmeRes.ok) {
                const data = await readmeRes.json()
                sha = data.sha
            }

            // Update/Create README
            await fetch(`https://api.github.com/repos/${username}/${repoName}/contents/README.md`, {
                method: 'PUT',
                headers,
                body: JSON.stringify({
                    message: 'docs: Add initial README',
                    content: Buffer.from(content).toString('base64'),
                    sha
                })
            })
        } catch (e) {
            console.warn('Failed to update README:', e)
        }

        return NextResponse.json({
            success: true,
            message: 'Repository created successfully!',
            repo_url: repo.html_url
        })

    } catch (error: any) {
        console.error('API Error:', error)
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 })
    }
}
